# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy	
# More GitHub Actions for Azure: https://github.com/Azure/actions	

name: Build and deploy Node.js app to Azure Web App - ct-covid	

on:	
  push:	
    branches:	
      - master	

jobs:	
  build-and-deploy:	
    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@master	

    - name: Set up Node.js version	
      uses: actions/setup-node@v1	
      with:	
        node-version: '12.x'	

    - name: npm install and build	
      run: |	
        npm install	
        npm run build --if-present	
        cp -r build/* .	
        rm -rf build	
        ls -la	
    - name: 'Deploy to Azure Web App'	
      uses: azure/webapps-deploy@v1	
      with:	
        app-name: 'ct-covid'	
        slot-name: 'production'	
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_274bdc30cc1b4b0f901f114d141a0301 }}	
        package: .