# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Release

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: release
      
    - name: Merge master
      run: |
        git merge --squash master
        
    - name: yarn build
      run: |
        yarn
        yarn build
        cp -r build/* .		
        rm -rf build	
        
    - name: Commit
      run: |
        git add --all .
        git commit -m "release `date -u`"
